version: '3.7'

services:
  db:
    image: mysql:8.0.17
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
volumes:
  db-data:
